name: Edwinverlaek
favicon: null
layout_spectrum: 0.23438736656680703
typography_spectrum: 0.9731574829202145
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3353693960234523
  lightness: 0.2619773296173662
  saturation: 0.9414097578264773
  rhythmicContrast: 0.38943934836424887
purpose: []
